export default [
  {
    avatar: 'https://avatars.dicebear.com/api/avataaars/testing-trial.svg',
    name: 'Admin Handal',
    email: 'adminhandal@gmail.com',
    role: 'Admin',
    status: 'Active',
    date: 'Mon Feb 03 2020 04:13:15 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://avatars.dicebear.com/api/avataaars/testing-trial2.svg',
    name: 'Monserrat Marquardt',
    email: 'MonserratMarquardt@gmail.com',
    role: 'user',
    status: 'Active',
    date: 'Fri Nov 29 2019 10:43:17 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://avatars.dicebear.com/api/avataaars/testing-geek.svg',
    name: 'Lonie Wyman',
    job: 'Legacyrogram@director.com',
    role: 'user',
    email: 'MonserratMarquardt@gmail.com',
    status: 'Not Active',
    date: 'Fri Apr 03 2020 03:07:53 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://avatars.dicebear.com/api/avataaars/testing-yaks.svg',
    name: 'Corine Abernathy',
    email: 'random@email',
    role:'user',
    status: 'Inactive',
    date: 'Fri Jun 21 2019 20:21:55 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://avatars.dicebear.com/api/avataaars/testing-tri2al.svg',
    name: 'Lorenz Botsford',
    email: 'Centraldeveloper@gmail.com',
    role: 'user',
    status: 'Inactive',
    date: 'Wed Aug 28 2019 15:31:43 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://avatars.dicebear.com/api/avataaars/testing-t212rial.svg',
    name: 'Everette Botsford',
    job: 'Product@Architect.com',
    role: 'user',
    status: 'Active',
    date: 'Thu Jan 16 2020 09:53:33 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://avatars.dicebear.com/api/avataaars/testing-trial.svg',
    name: 'Admin Handal',
    email: 'adminhandal@gmail.com',
    role: 'Admin',
    status: 'Active',
    date: 'Mon Feb 03 2020 04:13:15 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://avatars.dicebear.com/api/avataaars/testing-trial2.svg',
    name: 'Monserrat Marquardt',
    email: 'MonserratMarquardt@gmail.com',
    role: 'user',
    status: 'Active',
    date: 'Fri Nov 29 2019 10:43:17 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://avatars.dicebear.com/api/avataaars/testing-geek.svg',
    name: 'Lonie Wyman',
    job: 'Legacyrogram@director.com',
    role: 'user',
    email: 'MonserratMarquardt@gmail.com',
    status: 'Not Active',
    date: 'Fri Apr 03 2020 03:07:53 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://avatars.dicebear.com/api/avataaars/testing-yaks.svg',
    name: 'Corine Abernathy',
    email: 'random@email',
    role:'user',
    status: 'Inactive',
    date: 'Fri Jun 21 2019 20:21:55 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://avatars.dicebear.com/api/avataaars/testing-tri2al.svg',
    name: 'Lorenz Botsford',
    email: 'Centraldeveloper@gmail.com',
    role: 'user',
    status: 'Inactive',
    date: 'Wed Aug 28 2019 15:31:43 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://avatars.dicebear.com/api/avataaars/testing-t212rial.svg',
    name: 'Everette Botsford',
    job: 'Product@Architect.com',
    role: 'user',
    status: 'Active',
    date: 'Thu Jan 16 2020 09:53:33 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://avatars.dicebear.com/api/avataaars/testing-trial.svg',
    name: 'Admin Handal',
    email: 'adminhandal@gmail.com',
    role: 'Admin',
    status: 'Active',
    date: 'Mon Feb 03 2020 04:13:15 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://avatars.dicebear.com/api/avataaars/testing-trial2.svg',
    name: 'Monserrat Marquardt',
    email: 'MonserratMarquardt@gmail.com',
    role: 'user',
    status: 'Active',
    date: 'Fri Nov 29 2019 10:43:17 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://avatars.dicebear.com/api/avataaars/testing-geek.svg',
    name: 'Lonie Wyman',
    job: 'Legacyrogram@director.com',
    role: 'user',
    email: 'MonserratMarquardt@gmail.com',
    status: 'Not Active',
    date: 'Fri Apr 03 2020 03:07:53 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://avatars.dicebear.com/api/avataaars/testing-yaks.svg',
    name: 'Corine Abernathy',
    email: 'random@email',
    role:'user',
    status: 'Inactive',
    date: 'Fri Jun 21 2019 20:21:55 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://avatars.dicebear.com/api/avataaars/testing-tri2al.svg',
    name: 'Lorenz Botsford',
    email: 'Centraldeveloper@gmail.com',
    role: 'user',
    status: 'Inactive',
    date: 'Wed Aug 28 2019 15:31:43 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://avatars.dicebear.com/api/avataaars/testing-t212rial.svg',
    name: 'Everette Botsford',
    job: 'Product@Architect.com',
    role: 'user',
    status: 'Active',
    date: 'Thu Jan 16 2020 09:53:33 GMT-0300 (Brasilia Standard Time)',
  },
]
